### ISSUE TITLE
FSCaptureSetup注册机 这个文件被感染 注意用杀毒软件 清除感染 否则会感染全盘文件

### ISSUE THREAD

**Issue by LFYG** [woytu/UseNotes#1]
FSCaptureSetup注册机.exe  文件MD5: 840bd7173ee0017575f71de9c99e7dcb
这个文件已被木马感染 
详情查看：https://habo.qq.com/file/showdetail?md5=840bd7173ee0017575f71de9c99e7dcb&pk=ADwGZl1kB2IIOVs6

**Comment by woytu** [comment]
感谢反馈，已做删除处理
