### ISSUE TITLE
咨询vue press

### ISSUE THREAD

**Issue by kame000** [woytu/UseNotes#2]
![image](https://user-images.githubusercontent.com/20923887/63283257-5327e900-c2e3-11e9-8b76-022818cfff30.png)
主要想咨询下，想这种文章类的，不能匹配相对文件夹下的 md文件，进行正则解析吗？

还是需要手动一个一个添加。

博主有时间的话帮忙回答下，我想从hexo 转过来。如果太麻烦就不准备迁移了

**Comment by kame000** [comment]
![image](https://user-images.githubusercontent.com/20923887/63283421-b9ad0700-c2e3-11e9-90f3-3bca83ea36cf.png)

**Comment by woytu** [comment]
> ![image](https://user-images.githubusercontent.com/20923887/63283257-5327e900-c2e3-11e9-8b76-022818cfff30.png)
> 主要想咨询下，想这种文章类的，不能匹配相对文件夹下的 md文件，进行正则解析吗？
> 
> 还是需要手动一个一个添加。
> 
> 博主有时间的话帮忙回答下，我想从hexo 转过来。如果太麻烦就不准备迁移了

## 参考
[https://github.com/woytu/UseNotes-vuepress/blob/d608615fedeb88ecc3c9a719bf784e904d7ee92a/.vuepress/config.js#L59](https://github.com/woytu/UseNotes-vuepress/blob/d608615fedeb88ecc3c9a719bf784e904d7ee92a/.vuepress/config.js#L59)

[https://github.com/woytu/UseNotes-vuepress/blob/d608615fedeb88ecc3c9a719bf784e904d7ee92a/.vuepress/utils.js#L341](https://github.com/woytu/UseNotes-vuepress/blob/d608615fedeb88ecc3c9a719bf784e904d7ee92a/.vuepress/utils.js#L341)

### 因为vuepress在提交仓库前需要编译，所以你可以自定义一个工具类，一劳永逸

**Comment by woytu** [comment]
### 还有，如果不想用编译的话，可以参考这个仓库  https://github.com/woytu/UseNotes-docsify 定义好入口文件和工具后，只需要编辑md文件并提交即可
