### ISSUE TITLE
请尝试一下我的开源项目

### ISSUE THREAD

**Issue by wataru-c** [woytu/UseNotes#8]
你好，我注意到你在 https://www.bajins.com/System/Windows.html 内记录了很多 Windows 安装配置心得

如果你觉得很麻烦，不如试试把安装代码写到 [setupfw/win-sf](https://github.com/setupfw/win-sf) 自动部署框架内。欢迎使用或二次开发

附：[v2ex 介绍贴](https://v2ex.com/t/894560)

**Comment by bajins** [comment]
一般简单使用是不需要一个笨重的框架应用的
